/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d5414802e8ab75d05c74293
*
* You will get 10% discount for each one of your friends
* 
*/
package com.crosswalk.db.crosswalk_db.service.base;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;


import com.crosswalk.db.crosswalk_db.entity.Crosswalk;

import com.crosswalk.db.crosswalk_db.repositories.CrosswalkRepository;

@Service
@Transactional
public class CrosswalkBaseService {

	
	@Autowired
	CrosswalkRepository crosswalkRepository;


    // CRUD METHODS
    
    // CRUD - CREATE
    
	public Crosswalk insert(Crosswalk crosswalk) {
		return crosswalkRepository.save(crosswalk);
	}
	
	// CRUD - REMOVE
    
	public void delete(Long id) {
		crosswalkRepository.delete(id);
	}

	// CRUD - GET ONE
    	
	public Crosswalk getOne(Long id) {
		return crosswalkRepository.findOne(id);
	}

    	
    // CRUD - GET LIST
    	
	public List<Crosswalk> getAll() {
		List<Crosswalk> list = new ArrayList<>();
		crosswalkRepository.findAll().forEach(list::add);
		return list;
	}
	

}
